# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descriptions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('fold', models.FloatField(default=0, verbose_name='\u041a\u0440\u0430\u0442\u043d\u043e\u0441\u0442\u044c')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('fold', models.FloatField(default=0, verbose_name='\u041a\u0440\u0430\u0442\u043d\u043e\u0441\u0442\u044c (\u0432\u0435\u0440\u043e\u044f\u0442\u043d\u043e\u0441\u0442\u044c \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0434\u0430\u043d\u043d\u043e\u0439 \u0443\u0441\u043b\u0443\u0433\u0438)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.ServiceDescription', verbose_name='\u0423\u0441\u043b\u0443\u0433\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentDescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b')),
                ('group_number', models.IntegerField(default=0, verbose_name='\u2116 \u0433\u0440\u0443\u043f\u043f\u044b \u0412\u041c\u041f')),
                ('vmp_type_name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0432\u0438\u0434\u0435 \u0412\u041c\u041f')),
                ('mkb_code', models.IntegerField(default=0, verbose_name='\u041a\u043e\u0434 \u043f\u043e \u041c\u041b\u0411 - 10')),
                ('patient_type', models.CharField(max_length=30, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u0430')),
                ('treatment_type', models.CharField(max_length=50, verbose_name='\u0412\u0438\u0434 \u043b\u0435\u0447\u0435\u043d\u0438\u044f')),
                ('cure_avg_time', models.IntegerField(default=0, verbose_name='\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u043f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u043b\u0435\u0447\u0435\u043d\u0438\u044f')),
                ('blood_notblood_descr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.SuppliesDescriptionModel', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u043f\u0430\u0440\u0430\u0442\u043e\u0432 \u043a\u0440\u043e\u0432\u0438 \u0438 \u043a\u0440\u043e\u0432\u043e\u0437\u0430\u043c\u0435\u043d\u0438\u0442\u0435\u043b\u0435\u0439')),
                ('drugs_decr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='descriptions.MethodDrugsDescription', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043b\u0435\u043a\u0430\u0440\u0442\u0432\u0435\u043d\u043d\u044b\u0445 \u0441\u0440\u0435\u0434\u0441\u0442\u0432')),
                ('implant_descr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implant', to='descriptions.SuppliesDescriptionModel', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0438\u043c\u043f\u043b\u0430\u043d\u0442\u043e\u0432')),
                ('nutritional_care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NutritionalCare', verbose_name='\u0412\u0438\u0434\u044b \u043b\u0435\u0447\u0435\u0431\u043d\u043e\u0433\u043e \u043f\u0438\u0442\u0430\u043d\u0438\u044f')),
                ('service_list', models.ManyToManyField(to='core.Service', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u0443\u0441\u043b\u0443\u0433')),
            ],
        ),
    ]
