# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enchiridions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugsDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('fold', models.FloatField(default=0, verbose_name='\u041a\u0440\u0430\u0442\u043d\u043e\u0441\u0442\u044c (\u0432\u0435\u0440\u043e\u044f\u0442\u043d\u043e\u0441\u0442\u044c \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u043f\u0440\u0438\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u0441\u0440\u0435\u0434\u0441\u0442\u0432\u0430 \u043f\u0440\u0438 \u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0438 \u0443\u0441\u043b\u0443\u0433\u0438)')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchiridions.DrugsModel', verbose_name='\u041b\u0435\u043a\u0430\u0440\u0442\u0432\u0435\u043d\u043d\u043e\u0435 \u0441\u0440\u0435\u0434\u0441\u0442\u0432\u043e')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.CharField(max_length=30, verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u0440\u0430\u0431\u0442\u044b')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('fold', models.FloatField(default=0, verbose_name='\u041a\u0440\u0430\u0442\u043d\u043e\u0441\u0442\u044c (\u0432\u0435\u0440\u043e\u044f\u0442\u043d\u043e\u0441\u0442\u044c \u043f\u0440\u0438\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u043e\u0431\u043e\u0440\u0443\u0434\u043e\u0432\u0430\u043d\u0438\u044f \u043f\u0440\u0438 \u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0438 \u0443\u0441\u043b\u0443\u0433\u0438)')),
                ('cure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchiridions.MainCureModel', verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0435 \u0441\u0440\u0435\u0434\u0441\u0442\u0432\u043e')),
            ],
        ),
        migrations.CreateModel(
            name='MethodDrugsDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fold', models.FloatField(default=0, verbose_name='\u041a\u0440\u0430\u0442\u043d\u043e\u0441\u0442\u044c \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f')),
                ('unit', models.CharField(max_length=20, verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f')),
                ('dose_avg_day', models.IntegerField(default=0, verbose_name='\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u0441\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0434\u043e\u0437\u0430')),
                ('dose_avg_course', models.IntegerField(default=0, verbose_name='\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u043a\u0443\u0440\u0441\u043e\u0432\u0430\u044f \u0434\u043e\u0437\u0430')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchiridions.DrugsModel', verbose_name='\u041b\u0435\u043a\u0430\u0440\u0442\u0432\u0435\u043d\u043d\u043e\u0435 \u0441\u0440\u0435\u0434\u0441\u0442\u0432\u043e')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'visit', '\u041f\u0440\u0438\u0435\u043c (\u043e\u0441\u043c\u043e\u0442\u0440, \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f) \u0438 \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u043a \u0432\u0440\u0430\u0447\u0430-\u0441\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u0430'), (b'inst_research', '\u0418\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u0430\u043b\u044c\u043d\u044b\u0435 \u043c\u0435\u0442\u043e\u0434\u044b \u0438\u0441\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f'), (b'nonmedicamental', '\u041d\u0435\u043c\u0435\u0434\u0438\u043a\u043e\u043c\u0435\u043d\u0442\u043e\u0437\u043d\u044b\u0435 \u043c\u0435\u0442\u043e\u0434\u044b \u043f\u0440\u043e\u0444\u0438\u043b\u0430\u043a\u0442\u0438\u043a\u0438 \u043b\u0435\u0447\u0435\u043d\u0438\u044f \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u043e\u0439 \u0440\u0435\u0430\u0431\u0438\u043b\u0438\u0442\u0430\u0446\u0438\u0438'), (b'procedure', '\u0425\u0438\u0440\u0443\u0440\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0435, \u044d\u043d\u0434\u043e\u043d\u043e\u0441\u043a\u043e\u043f\u0438\u0447\u0435\u0441\u043a\u0438\u0435, \u044d\u043d\u0434\u043e\u0432\u0430\u0441\u043a\u0443\u043b\u044f\u0440\u043d\u044b\u0435 \u0438 \u0434\u0440\u0443\u0433\u0438\u0435 \u043c\u0435\u0442\u043e\u0434\u044b, \u0442\u0440\u0435\u0431\u0443\u044e\u0449\u0438\u0435 \u0430\u043d\u0435\u0441\u0442\u0435\u0437\u0438\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u043e\u0433\u043e \u0438/\u0438\u043b\u0438 \u0440\u0435\u0430\u043d\u0438\u043c\u0430\u0442\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u043e\u0433\u043e \u0441\u043e\u043f\u0440\u043e\u0432\u043e\u0436\u0434\u0435\u043d\u0438\u044f'), (b'observation', '\u041d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0435 \u0438 \u0443\u0445\u043e\u0434 \u0437\u0430 \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u043e\u043c \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u0438\u043c\u0438 \u0440\u0430\u0431\u043e\u0442\u043d\u0438\u043a\u0430\u043c\u0438 \u0441\u043e \u0441\u0440\u0435\u0434\u043d\u0438\u043c \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u043c \u043e\u0431\u0440\u0430\u0437\u043e\u0432\u0430\u043d\u0438\u0435\u043c')], max_length=15, verbose_name='\u0412\u0438\u0434 \u0443\u0441\u043b\u0443\u0433\u0438')),
                ('code', models.IntegerField(verbose_name='\u041a\u043e\u0434 \u0443\u0441\u043b\u0443\u0433\u0438')),
                ('service_name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0443\u0441\u043b\u0443\u0433\u0438')),
                ('drugs_descr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.DrugsDescription')),
                ('equipment_descr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.EquipmentDescriptionModel')),
            ],
        ),
        migrations.CreateModel(
            name='SuppliesDescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.CharField(max_length=30, verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('fold', models.FloatField(default=0, verbose_name='\u041a\u0440\u0430\u0442\u043d\u043e\u0441\u0442\u044c (\u0432\u0435\u0440\u043e\u044f\u0442\u043d\u043e\u0441\u0442\u044c \u043f\u0440\u0438\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0437\u0430\u043f\u0430\u0441\u0430 \u043f\u0440\u0438 \u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0438 \u0443\u0441\u043b\u0443\u0433\u0438)')),
                ('supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchiridions.MedicalSuppliesModel', verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0437\u0430\u043f\u0430\u0441\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.CharField(max_length=30, verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u0440\u0430\u0431\u0442\u044b')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('fold', models.FloatField(default=0, verbose_name='\u041a\u0440\u0430\u0442\u043d\u043e\u0441\u0442\u044c (\u0432\u0435\u0440\u043e\u044f\u0442\u043d\u043e\u0441\u0442\u044c \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0430 \u043f\u0440\u0438 \u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0438 \u0443\u0441\u043b\u0443\u0433\u0438)')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchiridions.PositionModel', verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
            ],
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='supplies_descr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.SuppliesDescriptionModel'),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='work_decsr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.WorkDescriptionModel'),
        ),
    ]
